- hosts: nginx
  tasks:
          - name: "create users nginx"
            user:
                    name: public
                    password: "$6$L6.yR9/qVqWqQn$2zkxUPtzsWHPDFEHP/5dlQVQ9j5x2FslM1XeBVMgB0VsEE.0gel0q36jUK3.wVyP4MpevH8m1f.nGUfkv5hli/"
                    groups: "sudo"
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/public

- hosts: mysql
  tasks:
          - name: "create users database"
            user:
                    name: db
                    password: "$6$L6.yR9/qVqWqQn$2zkxUPtzsWHPDFEHP/5dlQVQ9j5x2FslM1XeBVMgB0VsEE.0gel0q36jUK3.wVyP4MpevH8m1f.nGUfkv5hli/"
                    groups: "sudo"
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/db

- hosts: 172.31.2.214
  tasks:
          - name: "create users backend"
            user:
                    name: be
                    password: "$6$L6.yR9/qVqWqQn$2zkxUPtzsWHPDFEHP/5dlQVQ9j5x2FslM1XeBVMgB0VsEE.0gel0q36jUK3.wVyP4MpevH8m1f.nGUfkv5hli/"
                    groups: "sudo"
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/be


- hosts: 172.31.2.170
  tasks:
          - name: "create users frontend1"
            user:
                    name: fe1
                    password: "$6$L6.yR9/qVqWqQn$2zkxUPtzsWHPDFEHP/5dlQVQ9j5x2FslM1XeBVMgB0VsEE.0gel0q36jUK3.wVyP4MpevH8m1f.nGUfkv5hli/"
                    groups: "sudo"
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/fe1

- hosts: 172.31.2.34
  tasks:
          - name: "create users frontend2"
            user:
                    name: fe2
                    password: "$6$L6.yR9/qVqWqQn$2zkxUPtzsWHPDFEHP/5dlQVQ9j5x2FslM1XeBVMgB0VsEE.0gel0q36jUK3.wVyP4MpevH8m1f.nGUfkv5hli/"
                    groups: "sudo"
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/fe2

- hosts: 172.31.2.122
  tasks:
          - name: "create users jenkins"
            user:
                    name: jk
                    password: "$6$L6.yR9/qVqWqQn$2zkxUPtzsWHPDFEHP/5dlQVQ9j5x2FslM1XeBVMgB0VsEE.0gel0q36jUK3.wVyP4MpevH8m1f.nGUfkv5hli/"
                    groups: "sudo"
                    state: present
                    shell: /bin/bash
                    system: no
                    createhome: yes
                    home: /home/jk

