- hosts: fe1:fe2
  tasks:
          - name: run dumbplay-fe
            command: docker run -p 3000:3000 -d frostmarry/dumbplay-fe:latest

- hosts: be
  tasks:
          - name: run dumbplay-be
            command: docker run -p 5000:5000 -d frostmarry/dumbplay-be:latest

- hosts: jk
  tasks:
          - name: run jenkins
            command: docker run -p 8080:8080 -p 50000:50000 -d -v jenkins_home:/usr/app jenkins/jenkins:lts

- hosts: ps
  tasks:
          - name: run prometheus
            command: docker run -p 9090:9090 -d prom/prometheus

- hosts: ps
  tasks:
          - name: run grafana
            command: docker run -d --name=grafana -p 3000:3000 grafana/grafana

