- hosts: be
  tasks:
          - name: git clone
            git:
                    repo: git@github.com:frostmarry/dumbplay-be.git
                    version: master
                    dest: ~/dumbplay-be/
                    accept_hostkey: yes

                    
- hosts: fe1:fe2 
  tasks:
          - name: git clone
            git:
                    repo: git@github.com:frostmarry/dumbplay-fe.git
                    version: master
                    dest: ~/dumbplay-fe/
                    accept_hostkey: yes

                    
