- hosts: ps
  tasks:
          - name: copy config
            copy:
                 src: prometheus.yml
                 dest: /home/ps/prometheus/prometheus.yml
          
          - name: Pull Prometheus
            docker_image:
                 name: prom/prometheus
                 pull: yes
          
          - name: run container 
            docker_container:
                   name: prometheus
                   image: prom/prometheus
                   ports:
                           - 9090:9090
                   volumes: /home/ps/prometheus:/etc/prometheus



