- hosts: db
  tasks:
          - name: install mysql
            package:
                    name: "{{item}}"
                    state: present
                    update-cache: yes
            loop:
                    - mysql-server
                    - python3-pymysql 

          - name: start mysql service
            service:
                    name: mysql
                    state: started
                    enabled: yes

          - name: create new user
            mysql_user:
                    name: "{{dbuser}}"
                    password: "{{dbpass}}"
                    priv: '*.*:ALL'
                    host: '%'
                    state: present
                    
          - name: create database
            mysql_db:
                    name: "{{dbname}}"
                    state: present           

          - name: change ip bind
            lineinfile:
                    path: /etc/mysql/mysql.conf.d/mysqld.cnf
                    regexp: '^bind-address'
                    line: 'bind-address = 172.31.2.178'
                    backup: yes
          
          - name: restart mysql
            service:
                    name: mysql
                    state: restarted